### ISSUE TITLE
建议使用python3+

### ISSUE THREAD

**Issue by Mr-xn** [hackxc/Pyhacker#1]
**建议使用`python3+`**

**Comment by hackxc** [comment]
感谢您的建议，很多初学者在刚学py的时候，使用py2居多，sqlmap也是从py2过来的，所以写了关于py2的思路，与py3大同小异，修改部分语法即可投入使用啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"东方有鱼名为咸"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 中午12:02
收件人:&nbsp;"hackxc/Pyhacker"<Pyhacker@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hackxc/Pyhacker] 建议使用python3+ (#1)





 
建议使用python3+

**Comment by Mr-xn** [comment]
- 加油
